# Site settings
title: Princeton Tonight
email: tonight@princeton.edu
description: > # this means to ignore newlines until "baseurl:"
  Princeton Tonight is Princeton University’s first and only broadcast
  television show!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://princetontonight.com" # the base hostname & protocol for your site
twitter_username: princetontonight
facebook_username: PrincetonTonight

# Build settings
markdown: kramdown

# Gems
plugins:
  - jekyll-sitemap

# Serve options
port: 8000
